### ISSUE TITLE
Can I use a random number generator inside a kernel? 

### ISSUE THREAD

**Issue by hkhirsh** [OceanParcels/parcels#1008]
I just started using Python and OceanParcels and this is my first time posting a question in Github. I am trying to incorporate kernels to unbeach particles that end up on land - adapted from @delandmeterp Philippe Delandmeter's code here: https://github.com/OceanParcels/Parcelsv2.0PaperNorthSeaScripts/blob/master/northsea_mp_kernels.py

If a particle is tagged as "beached" then I want to "unbeach" it by "bumping" the coordinates aka adding a random number to the latitude and longitude. I tried this: 

```
particle.lon += random.uniform(-0.05, 0.05)
particle.lat += random.uniform(-0.05, 0.05) 
```
  
But for some reason the random random number generator does not work inside a kernel (see full kernel below). I also tried `np.random.uniform`. It works fine if I run `random.uniform(-0.05, 0.05)` outside of the kernel. 

I am importing random like this: 
`from parcels import rng as random`

Philippe Delandmeter uses random.uniform in his BrownianMotion2D kernel so I'm not sure why it doesn't work inside a kernel for me. 

I get an error that says: 

> NotImplementedError: Cannot convert 'random' used in kernel to C-code

Thank you in advance for any advice! I really appreciate it!!

Here is the unbeaching kernel I am trying to use:

```

def UnBeaching(particle, fieldset, time):
    if particle.beached == 4:     #4 undicates that a particle has been beached
        print("RUNNING UNBEACHING FOR:")
        lat = particle.lat
        lon = particle.lon
        print(lat)
        print(lon)

        particle.lon += np.random.uniform(-0.05, 0.05)
        particle.lat += np.random.uniform(-0.05, 0.05) 

        print("New LATLON:")
        lat = particle.lat
        lon = particle.lon
        print(lat)
        print(lon)

        particle.beached = 0
        particle.unbeachCount += 1

```

**Comment by hrsdawson** [comment]
Thanks for posting @hkhirsh, I've just come across the same error. This has only happened to me since updating my Parcels to version 2.2.2. In v2.2.1 I could use `random.uniform(low, high)` inside a kernel but I now get the same `NotImplementedError` when using the newest version.

**Comment by reint-fischer** [comment]
Hi @hkhirsh, @hrsdawson,

Thanks for posting this. Since Parcels v.2.21, we have renamed `parcels.random` to `parcels.ParcelsRandom` see these release notes: https://github.com/OceanParcels/parcels/releases/tag/v2.2.1

We have updated this in our tutorials (e.g. [diffusion](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/tutorial_diffusion.ipynb)) but examples of code like the one you are using from Phillipe's project remain unchanged of course.

rewriting your import from:
`from parcels import rng as random`
to 
`from parcels import ParcelsRandom`
or
`from parcels import ParcelsRandom as random`

should fix this.

**Comment by hrsdawson** [comment]
Thank you @reint-fischer! I'd missed that update - works for me now.

**Comment by hkhirsh** [comment]
@reint-fischer thank you for letting us know about the renaming in the update! I am still getting the error (`NotImplementedError: Cannot convert 'random' used in kernel to C-code`) after rewriting my import line as you suggested. I'll check out the updated diffusion tutorial and see if I can figure out my issue. 

@hrsdawson, would you mind sharing how/where you are using random.uniform so I can compare how I am implementing it? 

Thank you both!

**Comment by hkhirsh** [comment]
@reint-fischer @hrsdawson disregard my previous issue! I had not changed `random.uniform` to `ParcelsRandom.uniform`. I feel silly about this oversight, but hopefully sharing my mishap will help someone else catch a similar issue!
