### ISSUE TITLE
Keyerror when calling computeTimeChunk

### ISSUE THREAD

**Issue by ignasivalles** [OceanParcels/parcels#546]
Hi! after updating the master branch yesterday, I got a KeyError I didn't have before... It seems somehow it's not reading the variables correctly. I add three fields of data, a 3D velocity field  (fieldset.from_nemo), and temperature and salinity from a regular field (field.from_netcdf).

Traceback (most recent call last):
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py", line 887, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'vomecrty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_NBC_GLORYS2V4_TRY.py", line 147, in <module>
    T=fieldset.computeTimeChunk(fieldset.U.grid.time_full[0], 1)
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels-2.0.0b1.dev35+g165e476-py3.7.egg/parcels/fieldset.py", line 591, in computeTimeChunk
    f.computeTimeChunk(data, tind)
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels-2.0.0b1.dev35+g165e476-py3.7.egg/parcels/field.py", line 927, in computeTimeChunk
    if len(filebuffer.data.shape) == 2:
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels-2.0.0b1.dev35+g165e476-py3.7.egg/parcels/field.py", line 1438, in data
    data = self.dataset[self.name]
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py", line 961, in __getitem__
    return self._construct_dataarray(key)
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py", line 890, in _construct_dataarray
    self._variables, name, self._level_coords, self.dims)
  File "/home/valles/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py", line 76, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'vomecrty'

**Comment by erikvansebille** [comment]
Thanks @ignasivalles, for reporting this bug. I've reproduced it and can confirm that this is indeed a bug, probably introduced in the last PR. I'll work on a fix over the coming days, so please stay tuned

In the meantime, a hack around is to go into `fieldset.py` and change line 265 from `if sameGrid:` to `if False:`

**Comment by ignasivalles** [comment]
Hi @erikvansebille just in case this is helpful: I tried the solution you mentioned and a similar error appears but that time with the temperature variable name, please note that I'm using field.from_netcdf (not fieldset.from_netcdf) to read temperature and salinity (so then after I can add both fields using fieldset.add_field).

Thank you!

**Comment by erikvansebille** [comment]
Hi @ignasivalles, thanks for noting this. So just to confirm, it _doesn't_ work with your `Field.from_netcdf()` and `Fieldset.add_field()` workflow? Or does it work that way? 

Can you send the full error message and the relevant bits of your script? That'll help with debugging

**Comment by ignasivalles** [comment]
this is the piece of code:

```python
import numpy as np
from parcels import FieldSet, Field, ParticleSet, JITParticle, AdvectionRK4, AdvectionRK4_3D, Variable, ErrorCode, ParticleFile, Variable, plotTrajectoriesFile
from datetime import datetime, date, timedelta as delta
from os import path
import math
from glob import glob

Ufiles    = sorted(glob('/mnt/lustre/users/valles/DATA/GLORYS/VelocityField/*gridU_R200303*.nc'))
Vfiles    = sorted(glob('/mnt/lustre/users/valles/DATA/GLORYS/VelocityField/*gridV_R200303*.nc'))
Wfiles    = sorted(glob('/mnt/lustre/users/valles/DATA/GLORYS/VelocityField/*gridW_R200303*.nc'))
TSfiles   = sorted(glob('/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_200303*.nc'))

mesh_mask = '/mnt/lustre/users/valles/DATA/GLORYS/VelocityField/ext-GLORYS2V4_mesh_mask.nc'
outdir    = '/mnt/lustre/users/valles/DATA/parcels_output/parcels-5SFGLORYS_TRY.nc'

filenames = {'U': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':Ufiles}, 
             'V': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':Vfiles}, 
             'W': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':Wfiles}}

variables = {'U': 'vozocrtx',
             'V': 'vomecrty',
             'W': 'vovecrtz'}

dimensions= {'U': {'lon':'glamf','lat':'gphif','depth':'depthw','time':'time_counter'},
             'V': {'lon':'glamf','lat':'gphif','depth':'depthw','time':'time_counter'}, 
             'W': {'lon':'glamf','lat':'gphif','depth':'depthw','time':'time_counter'}}

#indices_nemo = {'lat': range(199, 405), 'depth': range(0, 34)}

fieldset = FieldSet.from_nemo(filenames, variables, dimensions, tracer_interp_method='cgrid_tracer', allow_time_extrapolation=True)

#fieldset.W.set_scaling_factor(-1) # convert to downard vertical velocity

dimensionsT = {'data':'temperature','lon':'longitude','lat':'latitude','depth':'depth','time':'time'}
dimensionsS = {'data':   'salinity','lon':'longitude','lat':'latitude','depth':'depth','time':'time'}

#indicesTS   = {'lat': range(140, 340), 'depth': range(0, 34)}

T = Field.from_netcdf(TSfiles, 'T', dimensionsT, fieldtype='T',  allow_time_extrapolation=True)
S = Field.from_netcdf(TSfiles, 'S', dimensionsS, fieldtype='S',  allow_time_extrapolation=True)  

fieldset.add_field(T)
fieldset.add_field(S)
     
T=fieldset.computeTimeChunk(fieldset.U.grid.time_full[0], 1)
```
the following error appears after changing line 265 in ```fieldset.py``` as you mentioned above:

```python
KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py in _construct_dataarray(self, name)
    895         try:
--> 896             variable = self._variables[name]
    897         except KeyError:

KeyError: 'T'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-1-76312c14f302> in <module>
     44 
     45 
---> 46 T=fieldset.computeTimeChunk(fieldset.U.grid.time_full[0], 1)

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels-2.0.0b1.dev118+g15433b1-py3.7.egg/parcels/fieldset.py in computeTimeChunk(self, time, dt)
    589                 f.loaded_time_indices = range(3)
    590                 for tind in f.loaded_time_indices:
--> 591                     f.computeTimeChunk(data, tind)
    592                 f.data = f.reshape(data)
    593             elif g.update_status == 'updated':

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels-2.0.0b1.dev118+g15433b1-py3.7.egg/parcels/field.py in computeTimeChunk(self, data, tindex)
    925             if self.netcdf_engine != 'xarray':
    926                 filebuffer.name = filebuffer.parse_name(self.filebuffername)
--> 927             if len(filebuffer.data.shape) == 2:
    928                 data[tindex, 0, :, :] = filebuffer.data
    929             elif len(filebuffer.data.shape) == 3:

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels-2.0.0b1.dev118+g15433b1-py3.7.egg/parcels/field.py in data(self)
   1436             data = self.dataset
   1437         else:
-> 1438             data = self.dataset[self.name]
   1439         ti = range(data.shape[0]) if self.ti is None else self.ti
   1440         if len(data.shape) == 2:

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py in __getitem__(self, key)
    968 
    969         if hashable(key):
--> 970             return self._construct_dataarray(key)
    971         else:
    972             return self._copy_listed(np.asarray(key))

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py in _construct_dataarray(self, name)
    897         except KeyError:
    898             _, name, variable = _get_virtual_variable(
--> 899                 self._variables, name, self._level_coords, self.dims)
    900 
    901         coords = OrderedDict()

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py in _get_virtual_variable(variables, key, level_vars, dim_sizes)
     72         ref_var = dim_var.to_index_variable().get_level_variable(ref_name)
     73     else:
---> 74         ref_var = variables[ref_name]
     75 
     76     if var_name is None:

KeyError: 'T'

**Comment by erikvansebille** [comment]
OK, I've just merged #549, which may fix this issue too. Can you check if it works with the latest `master`?

Also, why don't you directly load all five fields using `FieldSet.from_nemo()`? E.g.
```
filenames = {'U': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':Ufiles}, 
             'V': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':Vfiles}, 
             'W': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':Wfiles},
             'T': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':TSfiles},
             'S': {'lon':mesh_mask, 'lat':mesh_mask, 'depth':Wfiles[0], 'data':TSfiles}}
```
and then similar for `viariables` and `dimensions`. This would also set the correct `interp_method=cgrid_tracer`  Why instead do you add the `T` and `S` fields later?

**Comment by ignasivalles** [comment]
in my case ```T``` and ```S``` are in a regular grid downloaded directly from CMEMS (http://marine.copernicus.eu/), not in nemo C grid

**Comment by erikvansebille** [comment]
OK I see. And does it work with the newest `master` branch with #549 included?

**Comment by ignasivalles** [comment]
Unfortunately not. Solved for variables read by ```FieldSet.from_nemo()``` but not variables read by ```Field.from_netcdf()```, maybe the bug isn't fixed in ```field.py```(?)

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py in _construct_dataarray(self, name)
    895         try:
--> 896             variable = self._variables[name]
    897         except KeyError:

KeyError: 'T'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-1-1f96990ff724> in <module>
     44 
     45 
---> 46 fieldset.computeTimeChunk(fieldset.U.grid.time_full[0], 1)

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels-2.0.0b1.dev118+g15433b1-py3.7.egg/parcels/fieldset.py in computeTimeChunk(self, time, dt)
    590                 f.loaded_time_indices = range(3)
    591                 for tind in f.loaded_time_indices:
--> 592                     f.computeTimeChunk(data, tind)
    593                 f.data = f.reshape(data)
    594             elif g.update_status == 'updated':

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels-2.0.0b1.dev118+g15433b1-py3.7.egg/parcels/field.py in computeTimeChunk(self, data, tindex)
    928             if self.netcdf_engine != 'xarray':
    929                 filebuffer.name = filebuffer.parse_name(self.filebuffername)
--> 930             if len(filebuffer.data.shape) == 2:
    931                 data[tindex, 0, :, :] = filebuffer.data
    932             elif len(filebuffer.data.shape) == 3:

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/parcels-2.0.0b1.dev118+g15433b1-py3.7.egg/parcels/field.py in data(self)
   1439             data = self.dataset
   1440         else:
-> 1441             data = self.dataset[self.name]
   1442         ti = range(data.shape[0]) if self.ti is None else self.ti
   1443         if len(data.shape) == 2:

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py in __getitem__(self, key)
    968 
    969         if hashable(key):
--> 970             return self._construct_dataarray(key)
    971         else:
    972             return self._copy_listed(np.asarray(key))

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py in _construct_dataarray(self, name)
    897         except KeyError:
    898             _, name, variable = _get_virtual_variable(
--> 899                 self._variables, name, self._level_coords, self.dims)
    900 
    901         coords = OrderedDict()

~/miniconda3/envs/py3_parcels/lib/python3.7/site-packages/xarray/core/dataset.py in _get_virtual_variable(variables, key, level_vars, dim_sizes)
     72         ref_var = dim_var.to_index_variable().get_level_variable(ref_name)
     73     else:
---> 74         ref_var = variables[ref_name]
     75 
     76     if var_name is None:

KeyError: 'T'

```

**Comment by erikvansebille** [comment]
OK, thanks for confirming that the bug still exists, albeit somewhat deeper in the code and in a more special use-case.

Could you add `print(fieldset.T.dataFiles)` and let me know what the output is?

**Comment by ignasivalles** [comment]
here it is:
```
['/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030301_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030302_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030303_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030304_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030305_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030306_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030307_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030308_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030309_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030310_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030311_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030312_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030313_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030314_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030315_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030316_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030317_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030318_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030319_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030320_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030321_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030322_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030323_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030324_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030325_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030326_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030327_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030328_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030329_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030330_TS.nc'
 '/mnt/lustre/users/valles/DATA/GLORYS/TempSal/GLORYS2V4_1dAV_Rgrid_20030331_TS.nc']
```

**Comment by erikvansebille** [comment]
OK, so the field is pointing to the right files, it seems (this was the original bug that you initially mentioned). 
Can you add a `print(dataset)` just above line 1441 of field.py? And then send the output?

**Comment by ignasivalles** [comment]
I guess you wanted to say ```self.dataset```? otherwise it says doesn't exist.

```python
    @property
    def data(self):
        if self.netcdf_engine == 'xarray':
            data = self.dataset
        else:
            print(self.dataset)
            data = self.dataset[self.name]
        ti = range(data.shape[0]) if self.ti is None else self.ti
``` 

so the output is:

```
<xarray.Dataset>
Dimensions:       (deptht: 55, time_counter: 1, x: 441, y: 706)
Coordinates:
    nav_lon       (y, x) float32 ...
    nav_lat       (y, x) float32 ...
  * deptht        (deptht) float32 0.50576 1.5558553 ... 1945.2955 2101.0266
  * time_counter  (time_counter) datetime64[ns] 2003-02-26T12:00:00
  * x             (x) int32 790 791 792 793 794 795 ... 1226 1227 1228 1229 1230
  * y             (y) int32 197 198 199 200 201 202 ... 897 898 899 900 901 902
Data variables:
    vozocrtx      (time_counter, deptht, y, x) float32 ...
    decoded       bool True
Attributes:
    Conventions:  CF-1.0
    file_name:    GLORYS2V4_y2003m02d26_gridU.nc
    institution:  MERCATOR OCEAN
    source:       NEMO
    TimeStamp:    2016-APR-25 11:16:32 GMT-0000
    references:   http://www.mercator-ocean.eu
```
repeated several times (I guess the number of files/each time step)

**Comment by erikvansebille** [comment]
Yes, indeed `self.dataset`.

The thing is that all these files are slightly different. Thi is the U file (because it has 
`file_name:    GLORYS2V4_y2003m02d26_gridU.nc` and `vozocrtx`).
Now, I'd like to see the _last_ one, the one before it breaks. Because that should be `GLORYS2V4_1dAV_Rgrid_20030301_TS.nc` for file_name and `T` for variable. 
So could you please upload the entire output (or add it as a file, if it's very long)?

**Comment by ignasivalles** [comment]
yep sorry I've just seen it, I show you the last one but also I enclose a text file with the entire output 
[issue_546.txt](https://github.com/OceanParcels/parcels/files/2919984/issue_546.txt)


```
<xarray.Dataset>
Dimensions:      (depth: 55, latitude: 541, longitude: 461, time: 1)
Coordinates:
  * depth        (depth) float32 0.50576 1.555855 2.667682 ... 1945.296 2101.027
  * latitude     (latitude) float32 -60.0 -59.75 -59.5 ... 74.5 74.75 75.0
  * time         (time) datetime64[ns] 2003-03-01T12:00:00
  * longitude    (longitude) float32 -90.0 -89.75 -89.5 ... 24.5 24.75 25.0
Data variables:
    salinity     (time, depth, latitude, longitude) float32 ...
    temperature  (time, depth, latitude, longitude) float32 ...
    decoded      bool True
Attributes:
    title:                              daily mean from GLORYS2V4
    easting:                            longitude
    northing:                           latitude
    history:                            2016/08/23 12:37:26 MERCATOR OCEAN Ne...
    source:                             MERCATOR GLORYS2V4
    institution:                        MERCATOR OCEAN
    references:                         http://www.mercator-ocean.fr
    comment:                            CMEMS product
    Conventions:                        CF-1.4
    domain_name:                        GL4
    FROM_ORIGINAL_FILE__field_type:     mean
    field_date:                         2015-12-29 00:00:00
    field_julian_date:                  24103.0
    julian_day_unit:                    days since 1950-01-01 00:00:00
    forecast_range:                     6-day_forecast
    forecast_type:                      nowcast
    bulletin_date:                      2015-12-30 00:00:00
    bulletin_type:                      operational
    FROM_ORIGINAL_FILE__longitude_min:  -180.0
    FROM_ORIGINAL_FILE__longitude_max:  179.75
    FROM_ORIGINAL_FILE__latitude_min:   -80.0
    FROM_ORIGINAL_FILE__latitude_max:   90.0
    z_min:                              0.50576
    z_max:                              5902.058
    _CoordSysBuilder:                   ucar.nc2.dataset.conv.CF1Convention
```

**Comment by erikvansebille** [comment]
Ah, so now I see the problem! With PR #549, we also changed the way that the variables in `Field.from_netcdf` is called. It now has to be a tuple `(variable_name_in_parcels, variable_name_in_netcdffile)`  So you should do 
```
T = Field.from_netcdf(TSfiles, ('T', 'temperature'), dimensionsT, fieldtype='T',  allow_time_extrapolation=True)
S = Field.from_netcdf(TSfiles, ('S', 'salinity'), dimensionsS, fieldtype='S',  allow_time_extrapolation=True)
```
Let me know if this works

**Comment by ignasivalles** [comment]
yes! now it's working

thank you!
