### ISSUE TITLE
AttributeError: 'VectorField' object has no attribute 'ccode_name'

### ISSUE THREAD

**Issue by lucvandenbulcke** [OceanParcels/parcels#937]
Hello,
I'm trying to read the Stokes drift velocity from CMEMS files, and add them to another (existing) fieldset
I tried like this:
`def get_wav_fields3(fieldset,WAV_path,mesh_mask):`
`    basepath = WAV_path + '2018/12/' + '/*.nc'`
`    fnames=[];`
`    fnames += sorted(glob(str(basepath)))`
`    filenames =  {'Us': {'lon': mesh_mask, 'lat': mesh_mask, 'data': fnames}, 'Vs': {'lon': mesh_mask, 'lat': mesh_mask, 'data': fnames}}`
`    dimensions = {'Us': {'lon': 'longitude', 'lat': 'latitude', 'time': 'time'},'Vs': {'lon': 'longitude', 'lat': 'latitude', 'time': 'time'}}`
`    variables =  {'Us': 'VSDX', 'Vs': 'VSDY'}`
`    fs=FieldSet.from_netcdf(filenames,variables,dimensions)`
`    UVs = VectorField('UVs', fs.Us, fs.Vs)`
`    fieldset.add_vector_field(UVs)`
`    return fieldset`

I also tried reading separately `Us` and `Vs` using Field.from_netcdf , then adding them directly to the `fieldset`, as well as creating a `UVs` VectorField and adding that also to `fieldset`

I tried also reading the longitude and latitude coordinates from the datafiles, rather than from a separate coordinates file.

If I'm not mistaken, the kernel can have just 1 fieldset argument, that's why I add the Stokes drift Vectorfield to an existing fieldset.

I then call a custom kernel with 2 velocity components:
`def Dbl_AdvectionRK4(particle, fieldset, time):`
`    # Double advection of particles using fourth-order Runge-Kutta integration`
`    # using velocities from both current and Stokes drift`
`    (u1c, v1c) = fieldset.UV[time, particle.depth, particle.lat, particle.lon]`
`    (u1s, v1s) = fieldset.UVs[time, particle.depth, particle.lat, particle.lon]`
`    u1 = u1c + u1s`
`    v1 = v1c + v1s`
`    lon1, lat1 = (particle.lon + u1*.5*particle.dt, particle.lat + v1*.5*particle.dt)`
and so on.

Whatever the choices above, during execution of the kernel, the following error pops up: _AttributeError: 'VectorField' object has no attribute 'ccode_name'_
Using the regular RK4 kernel works without problems, so the VectorField in the error must be the Stokes drift one.

What I am doing wrong, how can I have the C code find the _ccode_name_ attribute for the UVs VectorField  ?

Thank you !
Luc

PS. The reason for not simply using SummedField, is that the existing velocity in the fieldset is a NestedField ( #927  )

**Comment by erikvansebille** [comment]
Thanks for reporting, @lucvandenbulcke! Could you try also adding the individual  `fs.Us` and `fs.Us` fields separately to `fieldset`? It could be that invoking `fieldset.add_vector_field()` only adds the `VectorField` object, but not the underlying `Fields`. I.e.
```python
fieldset.add_field(fs.Us)
fieldset.add_field(fs.Vs)
UVs = VectorField('UVs', fs.Us, fs.Vs)
fieldset.add_vector_field(UVs)
```

If indeed also adding the two individual fields fixes the problem, then this clearly is a bug that should be fixed. But better to first know if this is the direction we should be going in

**Comment by lucvandenbulcke** [comment]
Thanks for your answer.
Unfortunately, adding the 2 individual fields separately, and then creating the vectorfield, does not solve the problem
Also, creating Us and Vs completely independently (using Field.from_netcdf) , adding them to the fieldset, then creating the vectorfield and adding it,  still leads to the same error.

**Comment by erikvansebille** [comment]
Hi @lucvandenbulcke. Strange that adding the fields independently didn't help for you.  I have now been able to reproduce your error (I think) in a simple unit test at https://github.com/OceanParcels/parcels/commit/b8ac9a42056f78aa10623828790155de72211122

I have also added a fix to that error, in a new PR at #938. Could you check if this PR works for you? Are you comfortable to run Parcels in 'developer mode'?

We're finalising a new release of Parcels, so would be nice if this PR can be merged into master before that, to fix this Issue

**Comment by lucvandenbulcke** [comment]
Hi @erikvansebille 
I tried using Parcels following the "developper" installation instructions. I had conda remove parcels, then git cloned the `bugfix_add_vectorfield` branch, and set it up using setup.py . I think all this went OK, and I can run the newly added test.

(py3_parcels) luc@thinkpad:/data/oceans/parcels/oceanparcels/tests$ python
Python 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 23:51:54) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from test_fieldset import *
>>> test_add_second_vector_field('jit')
WARNING: Casting lon data to np.float32
WARNING: Casting lat data to np.float32
INFO: Compiled JITParticleAdvectionRK4SampleUV2 ==> /tmp/parcels-1000/05723469cd06d1d616600459f41285fe_0.so
>>> 

However my original problem is not solved, the VectorField object still has no ccode_name attribute.
Would it help if I shared a few netcdf files with the coordinates, and with currents and with stokes drift, as well as my python scripts ?

Thank you so much for your help !

**Comment by erikvansebille** [comment]
Ah, that is surprising. Could you indeed send me a few netcdf files via WeTransfer or similar system? I'll then look into it

**Comment by lucvandenbulcke** [comment]
The files are here [https://we.tl/t-xyrnKjgdJo](url)
The zipfile contains both my python scripts and the velocity data files.

**Comment by erikvansebille** [comment]
OK, I found your bug. It's because you add the wave fields _after_ you created the Particle Set. If you move the call to `get_wav_fields3()` to before you create the `pset`, then the error disappears. Can you confirm that works, @lucvandenbulcke? 

In general, one shouldn't change the `FieldSet` anymore after you've created a ParticleSet. Perhaps we should make this clearer in the tutorials (@reint-fischer) and/or add warning messages (although I'm not really sure how to catch _all_ possible changes to FieldSet...)

**Comment by reint-fischer** [comment]
We've talked about adding a tutorial explaining the high-level structure of parcels simulations. This could definitely be included there.

**Comment by lucvandenbulcke** [comment]
Thank you very much for finding this !
Indeed now the error has disappeared.

Best regards,
Luc

**Comment by lucvandenbulcke** [comment]
If you still have the patience, I have another problem (maybe out-of-topic in this issue, although it's related to adding extra fields to existing fieldsets).

The currents (from my NestedFields) are properly converted from m/s to °/s , but the Stokes drift velocities are not converted.
Following the Units tutorial, I found this:
>>> fieldset.U.units
<parcels.tools.converters.GeographicPolar object at 0x7fed2bb75da0>
>>> fieldset.Us.units
<parcels.tools.converters.UnitConverter object at 0x7fed27338cf8>
I saw that for my Stokes drift fields, fieldset.U.fieldtype is 'Us' (and not U), is this why the unit is automatically put as "unitConverter" ?
Did I miss an option to indicate myself what unit should be used ?

Thank you once again!
